events {}

http {

    # ====== RATE LIMIT ZONES ======
    # 5 registrations per minute
    limit_req_zone $binary_remote_addr zone=register_limit:10m rate=5r/m;
    # 10 logins per minute
    limit_req_zone $binary_remote_addr zone=login_limit:10m rate=10r/m;
    # 20 logins per minute
    limit_req_zone $binary_remote_addr zone=bot_limit:10m rate=20r/m;

    limit_req_status 429;

    server {
        listen 80;
        listen 443 ssl;

        ssl_certificate     /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        error_page 429 = @rate_limited;

        # ====== REGISTER ======
        location /register {
            limit_req zone=register_limit burst=3 nodelay;

            proxy_pass http://backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # ====== LOGIN ======
        location /login {
            limit_req zone=login_limit burst=5 nodelay;

            proxy_pass http://backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # ====== Bot ======
        location /bot {
            # headers = {"X-Bot": "bot"}
            if ($http_x_bot != "telegram") {
                return 403 '{"detail": "Forbidden"}';
            }

            limit_req zone=bot_limit burst=10 nodelay;

            proxy_pass http://backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # ====== EVERYTHING ELSE ======
        location / {
            proxy_pass http://backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # ====== STATIC ======
        location /static/ {
            alias /usr/share/nginx/html/;
        }

        # ====== JSON 429 ======
        location @rate_limited {
            default_type application/json;
            return 429 '{"detail": "Too many requests"}';
        }
    }
}
